#!/usr/bin/env -S tsx
import fs from 'fs';
import path from 'path';

const OUT = path.join(__dirname, '../src/bitboards/attacks.tables.ts');

const BF = (n: number) => BigInt(n);
const BIT = (i: number) => 1n << BF(i);

function indexToCoord(index: number) { return { file: index % 8, rank: Math.floor(index / 8) }; }
function coordToIndex(f: number, r: number) { return r * 8 + f; }

function genRookMask(sq: number) {
  const { file, rank } = indexToCoord(sq);
  let mask = 0n;
  const dirs = [[1,0],[-1,0],[0,1],[0,-1]];
  for (const [dx,dy] of dirs) {
    let x = file + dx, y = rank + dy;
    while (x > 0 && x < 7 && y > 0 && y < 7) {
      mask |= BIT(coordToIndex(x,y));
      x += dx; y += dy;
    }
  }
  return mask;
}

function genBishopMask(sq: number) {
  const { file, rank } = indexToCoord(sq);
  let mask = 0n;
  const dirs = [[1,1],[-1,1],[1,-1],[-1,-1]];
  for (const [dx,dy] of dirs) {
    let x = file + dx, y = rank + dy;
    while (x > 0 && x < 7 && y > 0 && y < 7) {
      mask |= BIT(coordToIndex(x,y));
      x += dx; y += dy;
    }
  }
  return mask;
}

function slidingRook(sq: number, occ: bigint) {
  const { file, rank } = indexToCoord(sq);
  let attacks = 0n;
  const dirs = [[1,0],[-1,0],[0,1],[0,-1]];
  for (const [dx,dy] of dirs) {
    let x = file + dx, y = rank + dy;
    while (x >= 0 && x < 8 && y >= 0 && y < 8) {
      const i = coordToIndex(x,y);
      attacks |= BIT(i);
      if (occ & BIT(i)) break;
      x += dx; y += dy;
    }
  }
  return attacks;
}

function slidingBishop(sq: number, occ: bigint) {
  const { file, rank } = indexToCoord(sq);
  let attacks = 0n;
  const dirs = [[1,1],[-1,1],[1,-1],[-1,-1]];
  for (const [dx,dy] of dirs) {
    let x = file + dx, y = rank + dy;
    while (x >= 0 && x < 8 && y >= 0 && y < 8) {
      const i = coordToIndex(x,y);
      attacks |= BIT(i);
      if (occ & BIT(i)) break;
      x += dx; y += dy;
    }
  }
  return attacks;
}

function genOccupancies(bits: number[]) {
  const n = bits.length;
  const count = 1 << n;
  const occs: bigint[] = new Array(count);
  for (let idx = 0; idx < count; idx++) {
    let occ = 0n;
    for (let j = 0; j < n; j++) if (idx & (1<<j)) occ |= BIT(bits[j]);
    occs[idx] = occ;
  }
  return occs;
}

function generate() {
  const rook: any = { masks: [], bits: [], offsets: [], table: [] };
  const bishop: any = { masks: [], bits: [], offsets: [], table: [] };

  for (let sq = 0; sq < 64; sq++) {
    const mask = genRookMask(sq);
    const bits: number[] = [];
    for (let i = 0; i < 64; i++) if (mask & BIT(i)) bits.push(i);
    const occs = genOccupancies(bits);
    const attacks = occs.map((o) => slidingRook(sq, o));
    rook.masks.push(mask);
    rook.bits.push(bits);
    rook.offsets.push(rook.table.length);
    rook.table.push(...attacks);
    console.log(`rook sq ${sq} bits ${bits.length} entries ${1<<bits.length}`);
  }

  for (let sq = 0; sq < 64; sq++) {
    const mask = genBishopMask(sq);
    const bits: number[] = [];
    for (let i = 0; i < 64; i++) if (mask & BIT(i)) bits.push(i);
    const occs = genOccupancies(bits);
    const attacks = occs.map((o) => slidingBishop(sq, o));
    bishop.masks.push(mask);
    bishop.bits.push(bits);
    bishop.offsets.push(bishop.table.length);
    bishop.table.push(...attacks);
    console.log(`bishop sq ${sq} bits ${bits.length} entries ${1<<bits.length}`);
  }

  let out = "// Precomputed sliding attack tables (non-magic)\n";
  out += "// Generated by CoreJS/scripts/generate_attack_tables.ts\n\n";

  out += "export const RookMasks: bigint[] = [\n" + rook.masks.map((x: bigint) => '  0x' + x.toString(16) + 'n').join(',\n') + "\n];\n\n";
  out += "export const RookBits: number[][] = [\n" + rook.bits.map((b: number[]) => '  [' + b.join(', ') + ']').join(',\n') + "\n];\n\n";
  out += "export const RookOffsets: number[] = [\n" + rook.offsets.map((x: number) => '  ' + x).join(',\n') + "\n];\n\n";
  out += "export const RookAttacks: bigint[] = [\n" + rook.table.map((x: bigint) => '  0x' + x.toString(16) + 'n').join(',\n') + "\n];\n\n";

  out += "export const BishopMasks: bigint[] = [\n" + bishop.masks.map((x: bigint) => '  0x' + x.toString(16) + 'n').join(',\n') + "\n];\n\n";
  out += "export const BishopBits: number[][] = [\n" + bishop.bits.map((b: number[]) => '  [' + b.join(', ') + ']').join(',\n') + "\n];\n\n";
  out += "export const BishopOffsets: number[] = [\n" + bishop.offsets.map((x: number) => '  ' + x).join(',\n') + "\n];\n\n";
  out += "export const BishopAttacks: bigint[] = [\n" + bishop.table.map((x: bigint) => '  0x' + x.toString(16) + 'n').join(',\n') + "\n];\n\n";

  fs.writeFileSync(OUT, out, { encoding: 'utf8' });
}

generate();
