import { HalfMoveInfo } from "@dardino-chess/core";
import { describe, expect, it } from "vitest";
import { buildTreeMoves } from "./sp-solution-desc.helper";

describe("buildTreeMoves", () => {
  it("tree moves from direct in 2", () => {
    const moves: Array<HalfMoveInfo> = [
      {
        num: 1,
        extraMoves: [],
        from: "e4",
        to: "e3",
        isPromotion: false,
        type: "-",
        part: "r",
        piece: "",
        promotedPiece: "",
        threat: false,
        zugzwang: false,
        isCheck: false,
        isCheckMate: false,
        isStaleMate: false,
        isTry: false,
        refutes: false,
        isKey: false,
      },
      {
        num: 2,
        extraMoves: [],
        from: "c2",
        to: "e3",
        isPromotion: false,
        type: "*",
        part: "l",
        piece: "S",
        promotedPiece: "",
        threat: false,
        zugzwang: false,
        isCheck: false,
        isCheckMate: true,
        isStaleMate: false,
        isTry: false,
        refutes: false,
        isKey: false,
      },
      {
        num: 1,
        extraMoves: [],
        from: "c5",
        to: "c4",
        isPromotion: false,
        type: "-",
        part: "r",
        piece: "",
        promotedPiece: "",
        threat: false,
        zugzwang: false,
        isCheck: false,
        isCheckMate: false,
        isStaleMate: false,
        isTry: false,
        refutes: false,
        isKey: false,
      },
      {
        num: 2,
        extraMoves: [],
        from: "c8",
        to: "e7",
        isPromotion: false,
        type: "-",
        part: "l",
        piece: "S",
        promotedPiece: "",
        threat: false,
        zugzwang: false,
        isCheck: false,
        isCheckMate: true,
        isStaleMate: false,
        isTry: false,
        refutes: false,
        isKey: false,
      },
      {
        num: 1,
        extraMoves: [],
        from: "c2",
        to: "e3",
        isPromotion: false,
        type: "-",
        part: "l",
        piece: "S",
        promotedPiece: "",
        threat: false,
        zugzwang: false,
        isCheck: true,
        isCheckMate: false,
        isStaleMate: false,
        isTry: true,
        refutes: false,
        isKey: false,
      },
      {
        num: 1,
        extraMoves: [],
        from: "d5",
        to: "d4",
        isPromotion: false,
        type: "-",
        part: "r",
        piece: "K",
        promotedPiece: "",
        threat: false,
        zugzwang: false,
        isCheck: false,
        isCheckMate: false,
        isStaleMate: false,
        isTry: false,
        refutes: false,
        isKey: true,
      },
      {
        num: 1,
        extraMoves: [],
        from: "a3",
        to: "b2",
        isPromotion: false,
        type: "-",
        part: "l",
        piece: "B",
        promotedPiece: "",
        threat: true,
        zugzwang: false,
        isCheck: false,
        isCheckMate: false,
        isStaleMate: false,
        isTry: true,
        refutes: false,
        isKey: false,
      },
      {
        num: 2,
        extraMoves: [],
        from: "c2",
        to: "e3",
        isPromotion: false,
        type: "-",
        part: "l",
        piece: "S",
        promotedPiece: "",
        threat: false,
        zugzwang: false,
        isCheck: false,
        isCheckMate: true,
        isStaleMate: false,
        isTry: false,
        refutes: false,
        isKey: false,
      },
      {
        num: 1,
        extraMoves: [],
        from: "c5",
        to: "c4",
        isPromotion: false,
        type: "-",
        part: "r",
        piece: "",
        promotedPiece: "",
        threat: false,
        zugzwang: false,
        isCheck: false,
        isCheckMate: false,
        isStaleMate: false,
        isTry: false,
        refutes: false,
        isKey: true,
      },
      {
        num: 1,
        extraMoves: [],
        from: "h4",
        to: "e1",
        isPromotion: false,
        type: "-",
        part: "l",
        piece: "Q",
        promotedPiece: "",
        threat: true,
        zugzwang: false,
        isCheck: false,
        isCheckMate: false,
        isStaleMate: false,
        isTry: true,
        refutes: false,
        isKey: false,
      },
      {
        num: 2,
        extraMoves: [],
        from: "e1",
        to: "d2",
        isPromotion: false,
        type: "-",
        part: "l",
        piece: "Q",
        promotedPiece: "",
        threat: false,
        zugzwang: false,
        isCheck: false,
        isCheckMate: true,
        isStaleMate: false,
        isTry: false,
        refutes: false,
        isKey: false,
      },
      {
        num: 2,
        extraMoves: [],
        from: "e1",
        to: "d1",
        isPromotion: false,
        type: "-",
        part: "l",
        piece: "Q",
        promotedPiece: "",
        threat: false,
        zugzwang: false,
        isCheck: false,
        isCheckMate: true,
        isStaleMate: false,
        isTry: false,
        refutes: false,
        isKey: false,
      },
      {
        num: 1,
        extraMoves: [],
        from: "c5",
        to: "c4",
        isPromotion: false,
        type: "-",
        part: "r",
        piece: "",
        promotedPiece: "",
        threat: false,
        zugzwang: false,
        isCheck: false,
        isCheckMate: false,
        isStaleMate: false,
        isTry: false,
        refutes: false,
        isKey: false,
      },
      {
        num: 2,
        extraMoves: [],
        from: "c8",
        to: "e7",
        isPromotion: false,
        type: "-",
        part: "l",
        piece: "S",
        promotedPiece: "",
        threat: false,
        zugzwang: false,
        isCheck: false,
        isCheckMate: true,
        isStaleMate: false,
        isTry: false,
        refutes: false,
        isKey: false,
      },
      {
        num: 1,
        extraMoves: [],
        from: "e4",
        to: "e3",
        isPromotion: false,
        type: "-",
        part: "r",
        piece: "",
        promotedPiece: "",
        threat: false,
        zugzwang: false,
        isCheck: false,
        isCheckMate: false,
        isStaleMate: false,
        isTry: false,
        refutes: false,
        isKey: true,
      },
      {
        num: 1,
        extraMoves: [],
        from: "h4",
        to: "f2",
        isPromotion: false,
        type: "-",
        part: "l",
        piece: "Q",
        promotedPiece: "",
        threat: true,
        zugzwang: false,
        isCheck: false,
        isCheckMate: false,
        isStaleMate: false,
        isTry: true,
        refutes: false,
        isKey: false,
      },
      {
        num: 2,
        extraMoves: [],
        from: "f2",
        to: "d2",
        isPromotion: false,
        type: "-",
        part: "l",
        piece: "Q",
        promotedPiece: "",
        threat: false,
        zugzwang: false,
        isCheck: false,
        isCheckMate: true,
        isStaleMate: false,
        isTry: false,
        refutes: false,
        isKey: false,
      },
      {
        num: 1,
        extraMoves: [],
        from: "c5",
        to: "c4",
        isPromotion: false,
        type: "-",
        part: "r",
        piece: "",
        promotedPiece: "",
        threat: false,
        zugzwang: false,
        isCheck: false,
        isCheckMate: false,
        isStaleMate: false,
        isTry: false,
        refutes: false,
        isKey: false,
      },
      {
        num: 2,
        extraMoves: [],
        from: "c8",
        to: "e7",
        isPromotion: false,
        type: "-",
        part: "l",
        piece: "S",
        promotedPiece: "",
        threat: false,
        zugzwang: false,
        isCheck: false,
        isCheckMate: true,
        isStaleMate: false,
        isTry: false,
        refutes: false,
        isKey: false,
      },
      {
        num: 2,
        extraMoves: [],
        from: "c2",
        to: "b4",
        isPromotion: false,
        type: "-",
        part: "l",
        piece: "S",
        promotedPiece: "",
        threat: false,
        zugzwang: false,
        isCheck: false,
        isCheckMate: true,
        isStaleMate: false,
        isTry: false,
        refutes: false,
        isKey: false,
      },
      {
        num: 1,
        extraMoves: [],
        from: "e4",
        to: "e3",
        isPromotion: false,
        type: "-",
        part: "r",
        piece: "",
        promotedPiece: "",
        threat: false,
        zugzwang: false,
        isCheck: false,
        isCheckMate: false,
        isStaleMate: false,
        isTry: false,
        refutes: false,
        isKey: true,
      },
      {
        num: 1,
        extraMoves: [],
        from: "h4",
        to: "e4",
        isPromotion: false,
        type: "*",
        part: "l",
        piece: "Q",
        promotedPiece: "",
        threat: false,
        zugzwang: false,
        isCheck: true,
        isCheckMate: false,
        isStaleMate: false,
        isTry: true,
        refutes: false,
        isKey: false,
      },
      {
        num: 1,
        extraMoves: [],
        from: "d5",
        to: "e4",
        isPromotion: false,
        type: "*",
        part: "r",
        piece: "K",
        promotedPiece: "",
        threat: false,
        zugzwang: false,
        isCheck: false,
        isCheckMate: false,
        isStaleMate: false,
        isTry: false,
        refutes: false,
        isKey: true,
      },
      {
        num: 1,
        extraMoves: [],
        from: "h4",
        to: "f4",
        isPromotion: false,
        type: "-",
        part: "l",
        piece: "Q",
        promotedPiece: "",
        threat: true,
        zugzwang: false,
        isCheck: false,
        isCheckMate: false,
        isStaleMate: false,
        isTry: true,
        refutes: false,
        isKey: false,
      },
      {
        num: 2,
        extraMoves: [],
        from: "f4",
        to: "d2",
        isPromotion: false,
        type: "-",
        part: "l",
        piece: "Q",
        promotedPiece: "",
        threat: false,
        zugzwang: false,
        isCheck: false,
        isCheckMate: true,
        isStaleMate: false,
        isTry: false,
        refutes: false,
        isKey: false,
      },
      {
        num: 1,
        extraMoves: [],
        from: "e4",
        to: "e3",
        isPromotion: false,
        type: "-",
        part: "r",
        piece: "",
        promotedPiece: "",
        threat: false,
        zugzwang: false,
        isCheck: false,
        isCheckMate: false,
        isStaleMate: false,
        isTry: false,
        refutes: false,
        isKey: false,
      },
      {
        num: 2,
        extraMoves: [],
        from: "c2",
        to: "e3",
        isPromotion: false,
        type: "*",
        part: "l",
        piece: "S",
        promotedPiece: "",
        threat: false,
        zugzwang: false,
        isCheck: false,
        isCheckMate: true,
        isStaleMate: false,
        isTry: false,
        refutes: false,
        isKey: false,
      },
      {
        num: 1,
        extraMoves: [],
        from: "c5",
        to: "c4",
        isPromotion: false,
        type: "-",
        part: "r",
        piece: "",
        promotedPiece: "",
        threat: false,
        zugzwang: false,
        isCheck: false,
        isCheckMate: false,
        isStaleMate: false,
        isTry: false,
        refutes: false,
        isKey: false,
      },
      {
        num: 2,
        extraMoves: [],
        from: "c8",
        to: "e7",
        isPromotion: false,
        type: "-",
        part: "l",
        piece: "S",
        promotedPiece: "",
        threat: false,
        zugzwang: false,
        isCheck: false,
        isCheckMate: true,
        isStaleMate: false,
        isTry: false,
        refutes: false,
        isKey: false,
      },
      {
        num: 1,
        extraMoves: [],
        from: "e5",
        to: "f4",
        isPromotion: false,
        type: "*",
        part: "r",
        piece: "",
        promotedPiece: "",
        threat: false,
        zugzwang: false,
        isCheck: false,
        isCheckMate: false,
        isStaleMate: false,
        isTry: false,
        refutes: false,
        isKey: true,
      },
      {
        num: 1,
        extraMoves: [],
        from: "h4",
        to: "g4",
        isPromotion: false,
        type: "-",
        part: "l",
        piece: "Q",
        promotedPiece: "",
        threat: true,
        zugzwang: false,
        isCheck: false,
        isCheckMate: false,
        isStaleMate: false,
        isTry: false,
        refutes: false,
        isKey: true,
      },
      {
        num: 2,
        extraMoves: [],
        from: "g4",
        to: "d1",
        isPromotion: false,
        type: "-",
        part: "l",
        piece: "Q",
        promotedPiece: "",
        threat: false,
        zugzwang: false,
        isCheck: false,
        isCheckMate: true,
        isStaleMate: false,
        isTry: false,
        refutes: false,
        isKey: false,
      },
      {
        num: 1,
        extraMoves: [],
        from: "e4",
        to: "e3",
        isPromotion: false,
        type: "-",
        part: "r",
        piece: "",
        promotedPiece: "",
        threat: false,
        zugzwang: false,
        isCheck: false,
        isCheckMate: false,
        isStaleMate: false,
        isTry: false,
        refutes: false,
        isKey: false,
      },
      {
        num: 2,
        extraMoves: [],
        from: "c2",
        to: "e3",
        isPromotion: false,
        type: "*",
        part: "l",
        piece: "S",
        promotedPiece: "",
        threat: false,
        zugzwang: false,
        isCheck: false,
        isCheckMate: true,
        isStaleMate: false,
        isTry: false,
        refutes: false,
        isKey: false,
      },
      {
        num: 1,
        extraMoves: [],
        from: "c5",
        to: "c4",
        isPromotion: false,
        type: "-",
        part: "r",
        piece: "",
        promotedPiece: "",
        threat: false,
        zugzwang: false,
        isCheck: false,
        isCheckMate: false,
        isStaleMate: false,
        isTry: false,
        refutes: false,
        isKey: false,
      },
      {
        num: 2,
        extraMoves: [],
        from: "c8",
        to: "e7",
        isPromotion: false,
        type: "-",
        part: "l",
        piece: "S",
        promotedPiece: "",
        threat: false,
        zugzwang: false,
        isCheck: false,
        isCheckMate: true,
        isStaleMate: false,
        isTry: false,
        refutes: false,
        isKey: false,
      },
      {
        num: 1,
        extraMoves: [],
        from: "h4",
        to: "h6",
        isPromotion: false,
        type: "-",
        part: "l",
        piece: "Q",
        promotedPiece: "",
        threat: true,
        zugzwang: false,
        isCheck: false,
        isCheckMate: false,
        isStaleMate: false,
        isTry: true,
        refutes: false,
        isKey: false,
      },
      {
        num: 2,
        extraMoves: [],
        from: "c8",
        to: "e7",
        isPromotion: false,
        type: "-",
        part: "l",
        piece: "S",
        promotedPiece: "",
        threat: false,
        zugzwang: false,
        isCheck: false,
        isCheckMate: true,
        isStaleMate: false,
        isTry: false,
        refutes: false,
        isKey: false,
      },
      {
        num: 1,
        extraMoves: [],
        from: "g8",
        to: "e6",
        isPromotion: false,
        type: "-",
        part: "r",
        piece: "B",
        promotedPiece: "",
        threat: false,
        zugzwang: false,
        isCheck: false,
        isCheckMate: false,
        isStaleMate: false,
        isTry: false,
        refutes: false,
        isKey: false,
      },
      {
        num: 2,
        extraMoves: [],
        from: "h6",
        to: "e6",
        isPromotion: false,
        type: "*",
        part: "l",
        piece: "Q",
        promotedPiece: "",
        threat: false,
        zugzwang: false,
        isCheck: false,
        isCheckMate: true,
        isStaleMate: false,
        isTry: false,
        refutes: false,
        isKey: false,
      },
      {
        num: 1,
        extraMoves: [],
        from: "e4",
        to: "e3",
        isPromotion: false,
        type: "-",
        part: "r",
        piece: "",
        promotedPiece: "",
        threat: false,
        zugzwang: false,
        isCheck: false,
        isCheckMate: false,
        isStaleMate: false,
        isTry: false,
        refutes: false,
        isKey: true,
      },
      {
        num: 1,
        extraMoves: [],
        from: "h4",
        to: "h5",
        isPromotion: false,
        type: "-",
        part: "l",
        piece: "Q",
        promotedPiece: "",
        threat: true,
        zugzwang: false,
        isCheck: false,
        isCheckMate: false,
        isStaleMate: false,
        isTry: true,
        refutes: false,
        isKey: false,
      },
      {
        num: 2,
        extraMoves: [],
        from: "h5",
        to: "d1",
        isPromotion: false,
        type: "-",
        part: "l",
        piece: "Q",
        promotedPiece: "",
        threat: false,
        zugzwang: false,
        isCheck: false,
        isCheckMate: true,
        isStaleMate: false,
        isTry: false,
        refutes: false,
        isKey: false,
      },
      {
        num: 1,
        extraMoves: [],
        from: "c5",
        to: "c4",
        isPromotion: false,
        type: "-",
        part: "r",
        piece: "",
        promotedPiece: "",
        threat: false,
        zugzwang: false,
        isCheck: false,
        isCheckMate: false,
        isStaleMate: false,
        isTry: false,
        refutes: false,
        isKey: false,
      },
      {
        num: 2,
        extraMoves: [],
        from: "c8",
        to: "e7",
        isPromotion: false,
        type: "-",
        part: "l",
        piece: "S",
        promotedPiece: "",
        threat: false,
        zugzwang: false,
        isCheck: false,
        isCheckMate: true,
        isStaleMate: false,
        isTry: false,
        refutes: false,
        isKey: false,
      },
      {
        num: 1,
        extraMoves: [],
        from: "e4",
        to: "e3",
        isPromotion: false,
        type: "-",
        part: "r",
        piece: "",
        promotedPiece: "",
        threat: false,
        zugzwang: false,
        isCheck: false,
        isCheckMate: false,
        isStaleMate: false,
        isTry: false,
        refutes: false,
        isKey: true,
      },
      {
        num: 1,
        extraMoves: [],
        from: "g5",
        to: "h6",
        isPromotion: false,
        type: "-",
        part: "l",
        piece: "K",
        promotedPiece: "",
        threat: true,
        zugzwang: false,
        isCheck: false,
        isCheckMate: false,
        isStaleMate: false,
        isTry: true,
        refutes: false,
        isKey: false,
      },
      {
        num: 2,
        extraMoves: [],
        from: "h4",
        to: "d8",
        isPromotion: false,
        type: "-",
        part: "l",
        piece: "Q",
        promotedPiece: "",
        threat: false,
        zugzwang: false,
        isCheck: false,
        isCheckMate: true,
        isStaleMate: false,
        isTry: false,
        refutes: false,
        isKey: false,
      },
      {
        num: 1,
        extraMoves: [],
        from: "e4",
        to: "e3",
        isPromotion: false,
        type: "-",
        part: "r",
        piece: "",
        promotedPiece: "",
        threat: false,
        zugzwang: false,
        isCheck: false,
        isCheckMate: false,
        isStaleMate: false,
        isTry: false,
        refutes: false,
        isKey: false,
      },
      {
        num: 2,
        extraMoves: [],
        from: "c2",
        to: "e3",
        isPromotion: false,
        type: "*",
        part: "l",
        piece: "S",
        promotedPiece: "",
        threat: false,
        zugzwang: false,
        isCheck: false,
        isCheckMate: true,
        isStaleMate: false,
        isTry: false,
        refutes: false,
        isKey: false,
      },
      {
        num: 1,
        extraMoves: [],
        from: "g8",
        to: "e6",
        isPromotion: false,
        type: "-",
        part: "r",
        piece: "B",
        promotedPiece: "",
        threat: false,
        zugzwang: false,
        isCheck: false,
        isCheckMate: false,
        isStaleMate: false,
        isTry: false,
        refutes: false,
        isKey: true,
      },
      {
        num: 1,
        extraMoves: [],
        from: "c8",
        to: "e7",
        isPromotion: false,
        type: "-",
        part: "l",
        piece: "S",
        promotedPiece: "",
        threat: false,
        zugzwang: false,
        isCheck: true,
        isCheckMate: false,
        isStaleMate: false,
        isTry: true,
        refutes: false,
        isKey: false,
      },
      {
        num: 1,
        extraMoves: [],
        from: "d5",
        to: "d6",
        isPromotion: false,
        type: "-",
        part: "r",
        piece: "K",
        promotedPiece: "",
        threat: false,
        zugzwang: false,
        isCheck: false,
        isCheckMate: false,
        isStaleMate: false,
        isTry: false,
        refutes: false,
        isKey: true,
      },
    ];
    const tree = buildTreeMoves(moves);
    expect(tree.length).toBe(moves.length);
    expect(tree[0].parentId).toBeNull(); // 1...e4-e3
    expect(tree[0].lineAge).toBe("0");
    expect(tree[1].parentId).toBe(tree[0].id); // 2.Sc2*e3#
    expect(tree[1].lineAge).toBe("0|1");
    expect(tree[2].parentId).toBeNull(); // 1...c5-c4
    expect(tree[2].lineAge).toBe("2");
    expect(tree[3].parentId).toBe(tree[2].id); // 2.Sc8*e3#
    expect(tree[3].lineAge).toBe("2|3");
    expect(tree[4].parentId).toBeNull(); // 1.Sc2-e3 + ?
    expect(tree[4].lineAge).toBe("4");
    expect(tree[5].parentId).toBe(tree[4].id); // 1...Kd5-d4 !
    expect(tree[5].lineAge).toBe("4|5");
    expect(tree[6].parentId).toBeNull(); // 1.Ba3-b2 ? threat:
    expect(tree[6].lineAge).toBe("6");
    expect(tree[7].parentId).toBe(tree[6].id); // 2.Sc2-e3 #
    expect(tree[7].lineAge).toBe("6|7");
    expect(tree[8].parentId).toBe(tree[6].id); // 1...c5-c4 !
    expect(tree[8].lineAge).toBe("6|8");
    expect(tree[9].parentId).toBeNull();// 1.Qh4-e1 ? threat:
    expect(tree[9].lineAge).toBe("9");
    expect(tree[10].parentId).toBe(tree[9].id); // 2.Qe1-d2 #
    expect(tree[10].lineAge).toBe("9|10");
    expect(tree[11].parentId).toBe(tree[9].id); // 2.Qe1-d1 #
    expect(tree[11].lineAge).toBe("9|11");
    expect(tree[12].parentId).toBe(tree[9].id); // 1...c5-c4
    expect(tree[12].lineAge).toBe("9|12");
    expect(tree[13].parentId).toBe(tree[12].id); // 2.Sc8-e7 #
    expect(tree[13].lineAge).toBe("9|12|13");
    expect(tree[14].parentId).toBe(tree[9].id); // but 1...e4-e3 !
    expect(tree[14].lineAge).toBe("9|14");
    // test implementation goes here
  });
});
