name: CI - Push Master

on:
  push:
    branches:
      - master

jobs:
  ci:
    uses: ./.github/workflows/reusable-ci.yml

  deploy_nightly:
    needs: ci
    runs-on: ubuntu-22.04
    name: Deploy to Nightly
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Download web deploy artifact
        uses: actions/download-artifact@v4
        with:
          name: web-deploy
          path: ./deploy/web

      - name: Download api deploy artifact
        uses: actions/download-artifact@v4
        with:
          name: api-deploy
          path: ./deploy/api

      - name: Deploy to Azure Static Web Apps (Nightly)
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ORANGE_SEA_080BC3503 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/deploy/web"
          api_location: "/deploy/api"
          output_location: ""
          skip_app_build: true
          skip_api_build: true
          deployment_environment: "nightly"
